# Generated by Django 3.1.4 on 2020-12-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('menu_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=15)),
                ('order_date', models.DateField()),
                ('point', models.IntegerField()),
                ('order_no', models.IntegerField()),
            ],
            options={
                'db_table': 'ORDER_TB',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'USER_TB',
            },
        ),
    ]
